//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estate
    {
        public int ID { get; set; }
        public string Adress { get; set; }
        public int Postal { get; set; }
        public string City { get; set; }
        public int SpaceM2 { get; set; }
        public bool isSold { get; set; }
        public int Price { get; set; }
        public string Image { get; set; }
    }
}
